### PR TITLE
Space calls to the function to be tested to enhance readability

### PR DESCRIPTION
**Pull request by czipperz**

### CODE REVIEW

**Comment by czipperz** [comment]
https://github.com/haskell/haskell-mode/pull/1364

**Comment by gracjan** [comment]
You could have force-pushed to the old PR and github would do the right thing.

**Comment by czipperz** [comment]
@gracjan the problem was that I had to delete my fork so I could update it with the master branch. That killed GitHub

**Comment by ivan-m** [comment]
@czipperz in future, if you add this repository as an upstream branch you can then pull/rebase from here and then force push to your fork.

**Comment by gracjan** [comment]
No problem for me either way.

**Pull request merged**
