### PR TITLE
Add front-sticky property to read-only text in REPL

### PR DESCRIPTION
**Pull request by fice-t**
This makes it so that you can't insert new text inside read-only text.

This doesn't feel like the best way of doing it (namely the prompt-specific part), but the other ways that I could think of would need an overhaul of the system or they resulted in surprisingly hard to debug errors, so I just settled on this.

The main reason for this is to prevent people from inserting behind the read-only space at the end of the default prompt and wondering why they can't hit RET to evaluate their input (which happened to me enough times).

### CODE REVIEW

**Comment by gracjan** [comment]
Is #876 related?

**Comment by gracjan** [comment]
Ill merge this tomorrow, unless somebody else chimes in with comments. The `sticky` parts isn't exactly my area of expertise.

**Comment by fice-t** [comment]
I don't think so. It affected the spacemacs guys though (#895).

**Comment by geraldus** [comment]
One annoying thing related to read-only text in REPL is that if I yank output of invoked command and paste it as input for next command I can't modify it, and removing readonly text property is a headache (I guess there could be some silly solution which I'm not aware of).

**Comment by fice-t** [comment]
Shouldn't you be able to modify yanked read-only text? I'm able to with these changes.

Also I found this:
```
yank-excluded-properties is a variable defined in `simple.el'.
Its value is
(category field follow-link fontified font-lock-face help-echo intangible invisible keymap local-map mouse-face read-only yank-handler)


Documentation:
Text properties to discard when yanking.
The value should be a list of text properties to discard or t,
which means to discard all text properties.
```
which includes the read-only property.

**Pull request merged**
