### PR TITLE
Use haskell-process-compute-process-log-and-command in haskell-process-start

### PR DESCRIPTION
**Pull request by cocreature**
If you oppose to the indentation changes, I'll take those out. I just thought those lines were way too long. Also I'm a really bad lisper, so I hope I didn't break anything.

### CODE REVIEW

**Comment by chrisdone** [comment]
Can you explain the point of this so when I get time to merge it I'll know why? Cheers

**Comment by cocreature** [comment]
During refactoring somebody removed the process-log-and-compute function call which resulted in haskell-process-wrapper-function no longer being used. This commit uses the still existing process-log-and-compute function again so that haskell-process-wrapper-function is actually used.

**Comment by chrisdone** [comment]
Oh, `haskell-process-compute-process-log-and-command`. I see. I'll test it in a bit. Thanks

**Comment by cocreature** [comment]
Anything wrong with it or did you just not have time to look at it?

**Comment by chrisdone** [comment]
Looks okay. Tested it, didn't break anything. Merged.

**Pull request closed without merging**
