### PR TITLE
Introduce completion candidates limit, minor fixes

### PR DESCRIPTION
**Pull request by geraldus**
Don't merge yet, I didn't tested this stuff well and want to play with this before merge.  Please review.

### CODE REVIEW

**Comment by gracjan** [comment]
Please use defconst instead of defcustom. After enough of testing we can
arrive at a constant that will make almost everybody happy. If somebody
detect a use case where that number fails then we would like to receive a
pull request so that everybody benefits.

**Comment by geraldus** [comment]
@gracjan ok, I think a hundred completions is quite comfortable value.

**Comment by geraldus** [comment]
@gracjan I have no idea about this

```
In toplevel form:
haskell-sort-imports.el:128:1:Error: the function `copy-list' is not known to be defined.
make: *** [haskell-sort-imports.elc] Error 1
```

**Comment by gracjan** [comment]
Use `cl-copy-list` and do `(require 'cl-lib)` in the beginning of the file.

**Comment by geraldus** [comment]
Ok, but I didn't touch `haskell-sort-imports.el` myself.  Will create a separate PR for this issue.

**Comment by gracjan** [comment]
I've fixed copy-list problem, just rebase over current master and you should be fine.

**Comment by geraldus** [comment]
Cool, thanks (:

**Comment by geraldus** [comment]
I did some quick tests, with hundred candidates limit dabbrev completions are still quite slow for short prefixes (2-4 chars), but performance increases for long prefixes.  The most comfortable limit value for short prefixes for me is about 10-20 candidates.

I got some insight: what about to set candidates limit on the fly depending of prefix length, i.e. set smaller limit for short prefixes and increase it for long prefixes?

**Comment by gracjan** [comment]
I've never heard about dabbrev performance issues. Are you sure we are
using it right?

**Comment by geraldus** [comment]
@gracjan, maybe I've took wrong words, I'm talking about issue described in #741 (here is a [demo](https://drive.google.com/open?id=0BwLfIDb7xEV7d3Vzd1FkNWh6Z1k)).

**Comment by gracjan** [comment]
@geraldus: Code looks good. It would be good to find somebody besides me and you to play with this before merge.

**Comment by geraldus** [comment]
Surely, I want to make some more changes, e.g. #776.

**Comment by gracjan** [comment]
@geraldus: I was thinking about this a bit more. Questions:

1. Is that the limit is a problem only with dabbrev?
2. Is there a way to DO NOTHING about dabbrev in haskell-mode and leave this task to company-dabbrev-mode?

**Comment by geraldus** [comment]
@gracjan answers :D 

1. No, it is not.  **ikirill** also reported some issues about REPL completions with big projects, but in common case limit issue is more related to dabbrev/
2. I think that it is possible and I'm going to check it.  I was not aware about dabbrev customizations in haskell-mode and that company have dabbrev backend out of box also.  I will push more updates soon.

**Comment by geraldus** [comment]
@gracjan I've disabled dabbrev temporarily to test existing behaviour.  I've already noticed that now completion candidates in comments are case insensitive.  I need to find and look at mentioned dabbrev customizations in haskell-mode.

**Comment by gracjan** [comment]
@geraldus: I've found these custom variables:

- dabbrev-case-distinction
- dabbrev-case-fold-search
- dabbrev-case-replace

We can set the buffer-local so that case sensitivity is kept. Would that work for you?

**Comment by geraldus** [comment]
@gracjan I will be able this in about one or two days.

**Comment by geraldus** [comment]
There were made so many changes, I think we can close this for now, I'm still busy, apologize :(

**Comment by gracjan** [comment]
No problem. Take care of your stuff, return when you are ready. haskell-mode will be around.

**Pull request closed without merging**
