### PR TITLE
Ignore stack and cabal files from hasktags

### PR DESCRIPTION
**Pull request by sLite**
As discussed on IRC.

As the windows version didn't include a find not applied there, and i have no windows environment to test on.

### CODE REVIEW

**Comment by gracjan** [comment]
Very close. Note that `find` has `-prune` option that would help a lot because it can stop `find` from entering unwanted directories and doing a lot of useless work:

```
find . 
    -type d \( bad_directories \) -prune
    -o
    -type f \\( -name '*.hs' -or -name '*.lhs' -or -name '*.hsc' \\) -not \\( -name '#*' -or -name '.*' \\)
    -print0
```

Please change to using `-prune`. For more inspiration `rgrep` elisp function has a lot of logic like that.

**Comment by gracjan** [comment]
@sLite: Note also #964.

**Comment by sLite** [comment]
@gracjan had some time issues lately, but i will look into this by the end of the week.

But i'm afraid that my experience with EL isn't nearly enough to tackle #964 

Putting that aside, is the allegedly decrease in coverage something i have to care about to get this PR merged? I don't see how changing the find commandline should change code coverage, but maybe i'm missing something :>

**Comment by gracjan** [comment]
coverage is not a problem. coveralls seems to misreport this and that, we will fix the coverage reporting later. Right now this is just a hint not a rule.

**Comment by sLite** [comment]
I've changed the ignored directories to -prune and moved from ignoring ```./dist/build``` to ignoring the ```./dist``` as a whole.

Please tell me if you think that could cause any troubles.
I did this because sometimes (i'm not exactly sure when and why) stack or cabal also place ```.hs``` files in ```./dist/production```

**Comment by gracjan** [comment]
This is good as it is.

**Comment by gracjan** [comment]
Thanks.

**Pull request merged**
