### PR TITLE
emacs23 /cl-lib specific comments in README.md

### PR DESCRIPTION
**Pull request by PinkMushroom**
hey my first ever pull request. be gentle...

### CODE REVIEW

**Comment by gracjan** [comment]
Cool stuff!

Message is good and I would gladly accept it as it is.

We need to work a little on the form of the commits as we care about how the history looks like. Please do the following:

1. Squash the commit into one (google: "git squash" and it will tell you how to do this).
2. Push the improved request into current one by `git push origin +master`.
3. The commit message should roughly follow this http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

It is easier for you to develop on a branch next time so you might want to check out "git branch".

**Comment by PinkMushroom** [comment]
yeah, i think trying to figure out how to do what you're asking will take so long as to not be worthwhile.
(i'm a total git noob).
but thanks for the suggestion.  hopefully next time i can structure things better.

**Comment by gracjan** [comment]
In that case I did it for you. Here is what I did:

1. Invoke `git rebase` in interactive mode on the three commits:
    ```
    git rebase -i HEAD~3
    ``` 

2. Select the ones that are fixups and mark them as such
    ```
    pick d3fe383 added some help about cl-lib for emacs23
    fixup dd8a67e *** empty log message ***
    fixup 0636de2 well- the message is finally formatted properly- i hope
    ```
3. (If I were you I could update your branch, like this:
    ```
    git push origin +master
    ```
    but i had to create a new pull request #632).

**Comment by gracjan** [comment]
Merged this via #632.

**Comment by gracjan** [comment]
@PinkMushroom: You are in the [contributors list](https://github.com/haskell/haskell-mode/graphs/contributors) for haskell-mode! Welcome!

**Comment by PinkMushroom** [comment]
On Thu, 07 May 2015 01:08:17 -0700
gracjan <notifications@github.com> wrote:

> In that case I did it for you. Here is what I did:
> 
> 1. Invoke `git rebase` in interactive mode on the three commits:
>     ```
>     git rebase -i HEAD~3
>     ``` 
> 
> 2. Select the ones that are fixups and mark them as such
>     ```
>     pick d3fe383 added some help about cl-lib for emacs23
>     fixup dd8a67e *** empty log message ***
>     fixup 0636de2 well- the message is finally formatted properly- i hope
>     ```
> 3. (If I were you I could update your branch, like this:
>     ```
>     git push origin +master
>     ```
>     but i had to create a new pull request #632).
> 
> 
> 

Thank you very much !

Now I know a little more about git.

Using haskell-mode everyday now, hope to contribute more meaningfully in the future.

Brian

**Comment by gracjan** [comment]
Note 1: reporting issues is also a form of contribution.
Note 2: our current focus is to make haskell-mode more friendly to first
time users, so your initial experiences are super-important for us. Please
report what you see.

(I cannot promise we will fix everything, but we would like to know where
are the stumbling blocks).

**Pull request closed without merging**
