### PR TITLE
Fix for #1691: disable-obsolete-face-alias is defined to require three args

### PR DESCRIPTION
**Pull request by jfb-ampli**
... so we need to supply a non-sense third argument here.

### CODE REVIEW

**Comment by qcfu-bu** [comment]
I want to point out there's another instance of disable-obsolete-face-alias in haskell-customize.el

**Comment by jfb-ampli** [comment]
> I want to point out there's another instance of disable-obsolete-face-alias in haskell-customize.el. I changed both instances of mine.

Is there? On head, I see `define-obsolete-variable-alias`, which is a different macro (and I checked, it has the `&optional` marker)

**Comment by jfb-ampli** [comment]
`(defmacro define-obsolete-variable-alias (obsolete-name current-name
						 &optional when docstring)`

**Comment by qcfu-bu** [comment]
My bad, you are right. The one in customize is correct.

**Comment by purcell** [comment]
fixed separately in 38c512b, thanks.

**Pull request closed without merging**
