### PR TITLE
Handle operators in haskell-ident-pos-at-point too

### PR DESCRIPTION
**Pull request by geraldus**
Let's see will it pass the tests.  I think I can add some tests for operators too.

### CODE REVIEW

**Comment by geraldus** [comment]
And it turns that we can drop `haskell-completions-general-prefix` due to prefix grabber no longer handles comments and strings (this will be next PR).

**Comment by geraldus** [comment]
Don't merge this yet, this implementation is buggy :(

**Comment by gracjan** [comment]
I think this function should be compatible with `thing-at-point`. That one seems to be standard.

**Comment by geraldus** [comment]
@gracjan I agree, but not this time, ok? (:

**Comment by geraldus** [comment]
@gracjan please overview

**Comment by gracjan** [comment]
Looks good to me. Lets wait the usual two days so that other people may look at the code.

**Comment by geraldus** [comment]
@gracjan no one going to test this :relieved:

**Comment by gracjan** [comment]
Merged.

**Pull request merged**
