### PR TITLE
Make going forward defun work correctly with comments

### PR DESCRIPTION
**Pull request by czipperz**
I don't know how to write a test for this because it requires the buffer to be fontified, and I don't know how to do that in batch mode.

```
module Test where

{- documentation here -}
fun = 13

{- document this function -}
f = 23
```

This patch makes going forward defuns (`C-M-e`) correctly go over comments.
`M-< C-M-e` gets you to line 2, `C-M-e` again gets you to line 5, `C-M-e` again gets you to line 8.

Before it would take you to lines 4, 7, and 8, respectively.

### CODE REVIEW

**Comment by geraldus** [comment]
> it requires the buffer to be fontified, and I don't know how to do that in batch mode

If I'm not mistaken this should work for you:
```el
(ert-deftest haskell-mode-test ()
  (should (with-temp-buffer
            (haskell-mode) ;; enabling Haskell mode should fontify temporal buffer
            (eq t whatever))))
```

**Comment by czipperz** [comment]
Tried that, doesnt work

**Comment by czipperz** [comment]
Maybe I have to run `syntax-ppss-flush-cache` after adding the text... lol

**Comment by gracjan** [comment]
`(font-lock-fontify-buffer)` is what you are looking for.

**Comment by czipperz** [comment]
That works thanks!

**Comment by czipperz** [comment]
Force pushed squashed some tests in

**Pull request merged**
