### PR TITLE
Implement QuasiQuotes [quote| xx |] as string face

### PR DESCRIPTION
**Pull request by gracjan**

### CODE REVIEW

**Comment by gracjan** [comment]
Fixes #323.

**Comment by geraldus** [comment]
I'm curious is it possible to provide some way to fontify quasi quotes according to its syntax if it is exists like in org mode. For example I have package for Yesod's Shakespearen Templates highlighting and it will be very cool to apply fortification for such quasi quotes as `shamlet`, `hamlet`, `julius`, and etc.

**Comment by gracjan** [comment]
Possible and could be done as a next step. What you need is:

- a mapping `quoter` -> `mode`
- use the mapping to to `fontify-as-mode` on the string inside quasi quote

Pretty simple.

**Comment by geraldus** [comment]
If I'm not mistaken quoter to mode map will raise "reference to void variable" errors in case there is no dependent package installed. How to avoid this?

**Comment by gracjan** [comment]
I guess `(if (fbound `xxx-mode) ...)` is the way to go.

**Comment by geraldus** [comment]
I've thought about it, but I guess true branch of mentioned `if` expression will raise error any way.

**Pull request merged**
