### PR TITLE
Use more efficient looking-at-p instead of looking-at in most places

### PR DESCRIPTION
**Pull request by sergv**
Change `looking-at` calls into `looking-at-p`. The latter is more efficient as it does not clobber match-data. While the former is redundant in places where match-data is not used after call (through e.g. match-{beginning,end,string,string-no-properties} functions).

### CODE REVIEW

**Comment by gracjan** [comment]
Cool! Let me review this properly.

**Comment by gracjan** [comment]
Thanks for these changes, efficiency is very important. There are other places in the code that could use similar efficiency changes. Can you do some more?

**Comment by sergv** [comment]
This was mostly a brief skim through the code base. I made changes whenever I was confident it won't break anything. I'll try to do some more in the future.

**Comment by gracjan** [comment]
So this one didn't go very well, including a hanging emacs session. For example `haskell-decl-scan.el` is full of code fragments like:

```el
(if (looking-at "[ \t]*\\(\\sw+\\)")
    (progn
      (setq name (match-string-no-properties 1))
      (setq name-pos (match-beginning 1))
      (setq type 'class))))
```
So this change isn't as obvious as we thought.

**Comment by sergv** [comment]
Yes. It seems I missed something, unfortunately.

**Pull request merged**
