### PR TITLE
Stylish haskell after save

### LINKED ISSUE #256: `haskell-stylish-on-save` with Yasnippet + ghc-mod sometimes removes import list
Using `haskell-stylish-on-save` with Yasnippet's import snippet sometimes erases import list. It seems that this occur when the import order will be changes.

Example:

```haskell
module Main where
import Prelude
imp
```

Then hit `[TAB]` on right after `imp` and import `Language.Haskell.TH` using ghc-mod's function symbol completion:

```haskell
module Main where
import Prelude
import Language.Haskell.TH
```

Push `[TAB]` to exit snippet, and don't move caret from right after `TH`.
Hit `C-xC-s`, then import list vanishes!:

```haskell
module Main where
import 
```

Environment
------------------
* GNU Emacs 24.3.4 (x86_64-apple-darwin11.4.2, Carbon Version 1.6.0 AppKit 1138.51)
* yasnippet-20140314
* haskell-mode-20140330
* ghc-20140331

### LINKED ISSUE #788: haskell-stylish-on-save causes double saving
I'm using undo-tree saving, so it also saves twice.

Shouldn't `haskell-mode-stylish-buffer` be called before saving?
It operates on buffer, not on file on disk.

### LINKED ISSUE #1074: haskell-mode-stylish-buffer is called in haskell-mode-after-save-handler
Why AFTER save? Why not BEFORE?

Also `haskell-mode-after-save-handler` is pretty creepy as it conflicts with any other after save hook functions.

### PR DESCRIPTION
**Pull request by bergey**
Fixes #1074. Fixes #788. Fixes #256.

### CODE REVIEW

**Comment by bergey** [comment]
Whoops.  Force-pushed parenthesis fix.

**Comment by gracjan** [comment]
Nice triple kill! Thanks.

**Comment by WraithM** [comment]
I updated to the newest melpa version of haskell-mode today. With `haskell-stylish-on-save t` in my emacs config, haskell-mode reverts changes that I made on a save. The Messages buffer only says,

```
Saving file /path/to/my/haskell/File.hs...
Wrote /path/to/my/haskell/File.hs
```

If I comment out my `haskell-stylish-on-save t`, everything works again.

**Comment by gracjan** [comment]
@bergey: What can this be?

**Comment by gracjan** [comment]
Ha! See here: https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L824
 ```el
         (_errcode (with-temp-file tmp-file
		     (call-process cmd filename
				   (list (current-buffer) err-file) nil)))
```

Although there is a temp file generated, it is not used, the original filename is used and `stylish-haskell` replaces its contents.

**Comment by gracjan** [comment]
@bergey: can you fix this? Thanks.

**Comment by gracjan** [comment]
(note: I've reverted the change for now).

**Comment by bergey** [comment]
Sorry about that.  Thanks for the diagnosis and reverting for now.  I'll fix it, probably next weekend.

**Comment by gracjan** [comment]
Great!

**Comment by WraithM** [comment]
Thank you both for all of your hard work :)

**Comment by gracjan** [comment]
@WraithM, actually can you help us with this? You have the commits by @bergey and I've pointed you to the problem of using original file name instead of temporary file name. Can you try to fix this?

Helpful info how to pull a pull request is here: https://help.github.com/articles/checking-out-pull-requests-locally/

Can you give it a try?

**Comment by WraithM** [comment]
Yeah! I'm down to try. I'm a novice in elisp, but this is a good excuse to learn.

What would you recommend for setting up a development environment? Like, I have the melpa version of haskell-mode installed right now. Is there a good way to tell emacs to load up my fork instead? I've cloned my fork in my home directory (ie. `~/haskell-mode`)

**Comment by WraithM** [comment]
Nevermind. I think I figured it out. I just added my fork to the load-path, and that seemed to do it.

**Comment by gracjan** [comment]
Yes, `load-path` is the way to go!

**Comment by gracjan** [comment]
@WraithM, @bergey: Is this moving forward?

**Comment by bergey** [comment]
Sorry, I got busy with other projects, and don't foresee getting back to this.

**Comment by WraithM** [comment]
Yeah, I'm sorry :( I similarly got distracted with work. I'm going to work on this now.

**Comment by WraithM** [comment]
Okay, so I got it working, but errors from stylish-haskell get dumped into the buffer...

**Comment by WraithM** [comment]
Making a PR now so you guys can look at it

**Comment by WraithM** [comment]
https://github.com/haskell/haskell-mode/pull/1266

**Comment by WraithM** [comment]
https://github.com/haskell/haskell-mode/pull/1268

Okay!

**Pull request merged**
