### PR TITLE
Fix haskell-docs invocation.

### LINKED ISSUE #535: Import suggester always fails
```
Identifier `lift' not in scope, choose module to import? (y or n) y
Haskell process command errored with: (wrong-type-argument listp t)
```

This lead @chrisdone to the discovery of a sub-problem where `M-! haskell-docks <$> RET` fails because of the way <$> is being escaped. This is not an issue for functions like `lift` though.

### PR DESCRIPTION
**Pull request by gracjan**
Fixes #535.

### CODE REVIEW

**Comment by gracjan** [comment]
@LukeHoersten: can you review and merge?

**Comment by LukeHoersten** [comment]
Tested with:

```haskell
test = toUpper <$> Just "hey"
```
and got the following failure (including `*Messages*` context):

```
Not in scope: ‘toUpper’
Identifier `toUpper' not in scope, choose module to import? (y or n) y
Invalid face reference: ido-first-match-face [106 times]
Haskell process command errored with: (wrong-type-argument listp t)
```

I don't think this patch fixes the issue.

**Comment by gracjan** [comment]
Ugh. But we are one step forward. What are these 'face' errors? Do you have
some special ido setup?

**Comment by LukeHoersten** [comment]
I only have default ido. `ido-first-match-face` isn't listed as a valid function or variable on my emacs.

**Comment by LukeHoersten** [comment]
I tested with a clean emacs config and everything works fine. I tried and it works fine with `ido` in a clean config as well. Something else I have in my config is conflicting. We'll have to track it down but the `<$>` escape problem is fixed for sure.

**Pull request merged**
