### PR TITLE
Better string animation

### PR DESCRIPTION
**Pull request by gracjan**

### CODE REVIEW

**Comment by geraldus** [comment]
New animation a bit blurry

**Comment by gracjan** [comment]
Hmm, wrong version of imagemagick probably.

**Comment by alanz** [comment]
The new one is half the size in each dimension. Is this intended?

**Comment by gracjan** [comment]
Other images, those already present in documentation were made on non-retina computer. The new one is made on a retina one. Screen capture produces twice as big image on retina displays, so the natural step is to resize to 50%.

As I see all of those things produce artefacts. So how to make a screenshot that does not introduce issues?

**Pull request merged**
