### PR TITLE
Fix hoogle lookup from local servers

### PR DESCRIPTION
**Pull request by sheyll**
Use a better way to check if the hoogle process is alive: Instead of
checking if the corresponding buffer-name is an alive process, store the
process handle in a global variable and check that.

The problem is that when using 'hoogle-lookup-from-local' without any
hoogle server running, a new local hoogle server is started, but the
code fails to recognize that server is running and instead repeatedly
reports that the server is not running offering to start it.

### CODE REVIEW

**Comment by gracjan** [comment]
@sheyll: Have you had time to look into this?

**Comment by sheyll** [comment]
@gracjan is this ok now?

**Comment by gracjan** [comment]
Great, thanks.

The functionality around hoogle and hayoo could use refactoring and be merged. Can you look into improving code there?

**Comment by jb55** [comment]
I think you need to pass `--local` to hoogle otherwise it uses `file://` links and browsers refuse to open those. Should I PR this?

**Comment by jb55** [comment]
Not strictly related to this PR but I'm curious to why it's not there already because local hoogle links are broken for me otherwise...

**Comment by gracjan** [comment]
I do not understand... What file links?

**Comment by jb55** [comment]
Sorry, when running hoogle with `-d /path/to/docs`, which is the case for auto-generated nix environments:

`hoogle "$COMMAND" -d /nix/store/smcqcq332zwb9g6xqvdz4zsxgk3bm253-hoogle-local-0.1/share/doc/hoogle "$@"`

Without the `--local` flag, links to docs on the search results page are `file:///path/to/docs` instead of `http://localhost/file/path/to/docs` which prevents them from working due to security mechanisms in browsers.

I was just wondering if it makes to add `--local` while we're at it, or at least an option to customize the hoogle server arguments.

**Comment by gracjan** [comment]
I still do not get it.

If hoogle produces wrong kind of links that make hoogle unusable then that
is a bug in hoogle and should be fixed there, shouldn't it?

**Comment by jb55** [comment]
All I need is the ability to pass `--local` to `hoogle server`. I'll start a new issue.

**Pull request merged**
