### PR TITLE
Fix completion after operator

### LINKED ISSUE #1349: Completion and "."
In interactive-haskell-mode, when i try to complete something after a dot, it won't work. For example if i try to complete something like `Ssh.`, it won't show any completions. If i try to complete `Ssh`, it will show the expected candidates, e.g. `Ssh.noPasswords`. If it try to complete `Ssh.n`, it will also complete.

### PR DESCRIPTION
**Pull request by akermu**
Fix #1349

### CODE REVIEW

**Comment by gracjan** [comment]
Nice, thanks for putting this together. We must have some tests for this, at least 2x2=4 for nil/t for custom variable and two kinds of symbols (identifiers/operators).

**Comment by akermu** [comment]
Ok, I'll try to add them in the next few days.

**Comment by akermu** [comment]
I have a question: How should I design the tests? Would it be better to mock `haskell-completions-sync-repl-completion-at-point' or should I try to start a GHCi-session to test the functionality?

I'm in favor of the first option, as it has overall lower overhead.

**Comment by gracjan** [comment]
Yes, first option. There is no need to run ghci for this test.

**Comment by geraldus** [comment]
I believe first option is the only way to go (if I'm not mistaken we do not have GHC executable on Travis).

**Comment by akermu** [comment]
I have added some tests, which finally work now on travis.

**Comment by gracjan** [comment]
Great! Thanks!

**Comment by geraldus** [comment]
Thanks

**Pull request merged**
