### PR TITLE
Use functions `bobp' and `member' instead of manual implementations.

### PR DESCRIPTION
**Pull request by czipperz**
This simplifies the code, making it consistent and readable.

### CODE REVIEW

**Comment by czipperz** [comment]
@geraldus Your renaming is incorrect.  Look at the first edit:

    -       (let ((f (following-char)))
    -         (or (= f ?\t)		
    -             (= f ?\n)		
    -             (= f ? )))
    +       (member (following-char) '(?\t ?\n ?\ ))

This uses `member` instead of a manual implementation of it.

**Comment by geraldus** [comment]
@czipperz oh, yep, sorry for that!

**Comment by gracjan** [comment]
Nice to see that haskell-decl-scan is getting some love. It could use much more hugging.

**Comment by czipperz** [comment]
@gracjan Yea I fixed it up this summer.  Are there any more problems I could work on?

**Comment by gracjan** [comment]
@czipperz: plenty. You can take any of the issues reported and just try to fix it. If you are talking about haskell-decl-scan then know that this module does not support half of useful haskell syntax extensions available: type operators, view patterns, type families, gadts. There is plenty to do to bring it up to current haskell language.

**Comment by czipperz** [comment]
@gracjan With regards to the type operators, I can make it work if I replace the regular expressions with a function to recognize the beginning of functions.  I'm not sure if this will break anything, but I'll try it out.

**Pull request merged**
