### PR TITLE
Ensure directory exists before searching for a .cabal file

### PR DESCRIPTION
**Pull request by ivan-m**
As requested by @gracjan in #506, this makes `haskell-cabal-find-file` check that the provided directory actually exists before using it to search for a .cabal file.

### CODE REVIEW

**Comment by gracjan** [comment]
Did you know that you can just force-push new commits to old pull request branch and it will update properly? You do not have to create new pull requests. I find it slightly easier to just push fixed commits.

**Comment by ivan-m** [comment]
First time, no; second time, I accidentally deleted the commit and when I tried to force push the new commit it didn't register in the patch request to let me re-open it :s

**Comment by gracjan** [comment]
We should put this workflow on some kind of `contributing` page. It was a mystery for me too.

**Comment by gracjan** [comment]
I'd like to test this, how do I trigger the case you are solving here?

**Comment by ivan-m** [comment]
`(haskell-cabal-find-file "/path/to/nonexistent/directory/")`

**Pull request merged**
