### PR TITLE
Modernize haskell-font-lock-symbols.

### PR DESCRIPTION
**Pull request by gracjan**

### CODE REVIEW

**Comment by gracjan** [comment]
@purcell: I would appreciate a review and a merge.

**Comment by purcell** [comment]
You should probably explicitly set the coding for the file now that it contains the unicode chars.

I noticed the old code used `char-displayable-p` -- what case did that cover, and is it not needed any more?

**Comment by gracjan** [comment]
`char-displayable-p` seems to come from times when Emacs wasn't Unicode and font handling was subpar. Now it seems that it can display all glyphs in all practical situations.

**Comment by gracjan** [comment]
This file used to contain Unicode chars before my change. Still setting encoding explicitly seems like a good idea.

**Comment by purcell** [comment]
Done in e191f50

**Pull request merged**
