### PR TITLE
Differentiate Haddock and regular comments better

### PR DESCRIPTION
**Pull request by karljs**
Because this regular expression accepted many spaces it would lead to the problem that in the following example, the first line would be highlighted as a regular comment and the second as a Haddock comment.

    -- fn (Pattern x y) | fn2 x = True
    --                  | otherwise = fn y

Intuitively I think one space or tab should be fine for Haddock comments to keep working, but I would appreciate other people thinking about that independently before merging this.

### CODE REVIEW

**Comment by waern** [comment]
Yes, (double dash) Haddock comments must have the prefix "-- ", so one space is allowed only (and no tabs).
See: https://github.com/ghc/ghc/blob/master/compiler/parser/Lexer.x#L358

**Comment by gracjan** [comment]
@karljs: can you remove the \t as it is not legal there either. Thanks!

**Comment by gracjan** [comment]
@waern: thanks.

Summary:

For double-dash: double-dash plus exactly one space plus $docsym
For brace-dash: brace-dash plus optional one space plus $docsym
And docsym = [\| \^ \* \$]

is this correct?

**Comment by waern** [comment]
Correct.

**Comment by karljs** [comment]
Sorry, I pushed too early and don't want to squash a bunch of nonconsecutive commits.  I'll reopen a clean pull request for this as soon as possible.

**Pull request closed without merging**
