### PR TITLE
Fix tag generation to not read in lockfiles or other undesirables.

### PR DESCRIPTION
**Pull request by code-crimes**

### CODE REVIEW

**Comment by gracjan** [comment]
Why is this even going though GHCi shell and interactive mode? TAGS could be generated directly.

**Comment by gracjan** [comment]
Thanks.

**Comment by code-crimes** [comment]
Haha yeah I was wondering that as well, good point :smile:. Thanks for the merge.

**Comment by gracjan** [comment]
If you have time and skill, can you look into untangling this mess and
generating TAGS directly? I bet there is some premade ready code out there
in the internets that does exactly what we want.

**Comment by code-crimes** [comment]
Sure, I'm not the most fluent in elisp, but I'd be happy to give it a shot! By directly you just mean shelling out to find + hasktags instead of through this ghci weirdness, correct?

**Comment by gracjan** [comment]
Yes, exactly.

**Pull request merged**
