### PR TITLE
haskell-load: add haskell-goto-first-error

### PR DESCRIPTION
**Pull request by da-x**
I usually start to fix stuff from top to bottom. This helps finding the first error.

### CODE REVIEW

**Comment by gracjan** [comment]
Hi,

Good function. Is it connected to anything?

**Comment by da-x** [comment]
I set up my `haskell-goto-*` bindings to match those of my `flycheck` setup, which are different from the `haskell-interative-mode` defaults, which are `M-n` and `M-p` for `next` and `prev` respectively ever since 2012. I defer on this new binding for @chrisdone to decide.

**Comment by gracjan** [comment]
We can't burden our users to somehow discover that this exists and then bind the keys themselves.

For this PR to be merged we need:
- [ ] user interface element where it is bound (keybinding)
- [ ] documentation in `haskell-mode.texi`
- [ ] a unit test case

**Comment by da-x** [comment]
Added a binding. However, considering that `haskell-mode.texi` is very lacking around the `haskell-process` mode, and that the unit tests of `haskell-process` around UI are practically nonexistent, it's a bit over my head right now to extend on those. Do what you will :)

**Comment by bergey** [comment]
Finishing this PR is on my list, too.

**Comment by gracjan** [comment]
Good. Thanks.

**Pull request closed without merging**
