### PR TITLE
Use tags-table-list instead of tags-file-name

### PR DESCRIPTION
**Pull request by davidsiefert**
This way I can jump not only in the file I'm in, but to the library sources as well...

### CODE REVIEW

**Comment by chrisdone** [comment]
Neat!

**Comment by davidsiefert** [comment]
Sorry man, looks like I broke the build.... will figure it out...

**Comment by gracjan** [comment]
@davidsiefert: for your convenience:

    In toplevel form:
    haskell-commands.el:636:32:Error: malformed let binding: 
        `(add-to-list (quote tags-table-list) (haskell-session-tags-filename (haskell-process-session (car state))))'
    make: *** [haskell-commands.elc] Error 1

**Comment by gracjan** [comment]
@davidsiefert: is it working better now?

**Comment by gracjan** [comment]
@davidsiefert: is it working better now?

**Comment by LukeHoersten** [comment]
Fixed in #592

**Comment by davidsiefert** [comment]
Sorry for my inactivity--I never got a chance to look into this.  Thanks for taking ownership and adding this feature!  You guys rock!

**Pull request closed without merging**
