### PR TITLE
Enable lexical binding in every source lisp file

### LINKED ISSUE #815: Use lexical-binding in all source files
Lexical binding is available since Emacs 24 but can be used in way that is compatible with Emacs 23. Tasks to make this happen:

1. Add `;;; -*- lexical-binding: t -*-` to every `*.el` file.
2. Fix all warnings about unused lexical variables (be removing a variable or prepending underscore to its name).
3. Fix all errors about undefined lexical variables (if any).

Example of current output:

```
In toplevel form:
haskell-modules.el:51:1:Warning: Unused lexical argument `dontcreate'
haskell-modules.el:51:1:Warning: Unused lexical argument `session'
Wrote /Users/kazu/tmp/haskell-mode/haskell-modules.elc
```

### PR DESCRIPTION
**Pull request by deepfire**
Resolve #815.

### CODE REVIEW

**Comment by deepfire** [comment]
Note, how emacs 24.5.2 fails to detect some bindings as used..  Pretty amazed by the fact.

**Comment by deepfire** [comment]
@gracjan, there was one, yes, in `haskell-cabal-find-subsection`.

**Comment by gracjan** [comment]
Lets give this pull request 24h for other guys reading to chime in if they see anything wrong in here.

**Comment by syohex** [comment]
First line should be package declaration by Emacs packaging convention. So first line should be as below.

```lisp
 ;;; ghc-core.el --- Syntax highlighting module for GHC Core -*- lexical-binding: t -*-
```

Examples
- https://github.com/emacs-helm/helm/blob/875f0a2396c6dcee13be17eec4b507a908f2953e/helm.el#L1
- https://github.com/bbatsov/projectile/blob/926d6f7fafc8acab16b04de0b5b7b19f6062bfed/projectile.el#L1

**Comment by gracjan** [comment]
@deepfire, can you amend your first commit so that it follows generally accepted practice pointed out by @syohex?

**Comment by deepfire** [comment]
@gracjan, sure thing.

**Comment by deepfire** [comment]
Done.

**Comment by gracjan** [comment]
Thanks!

**Pull request merged**
