### PR TITLE
Use tags-table-list instead of tags-file-name

### PR DESCRIPTION
**Pull request by geraldus**

### CODE REVIEW

**Comment by gracjan** [comment]
In toplevel form:
haskell-commands.el:659:32:Error: malformed let binding: `(add-to-list (quote tags-table-list) (haskell-session-tags-filename (haskell-process-session (car state))))'
make: *** [haskell-commands.elc] Error 1

See here:

https://travis-ci.org/haskell/haskell-mode/jobs/59447137

**Comment by geraldus** [comment]
@gracjan indeed! Please ping me on IRC, when you'll be online.

**Comment by geraldus** [comment]
This is temporal variable, I

**Comment by gracjan** [comment]
Why did you close it?

**Comment by geraldus** [comment]
I don't know another way to get rid of all old commits to a single one yet.

**Comment by gracjan** [comment]
This: `git rebase -i`, squash squash squash, `git push origin +tmp`.

**Comment by geraldus** [comment]
Will try next time! Here is new PR https://github.com/haskell/haskell-mode/pull/592

**Pull request closed without merging**
