### PR TITLE
Resurrect Emacs23 support

### PR DESCRIPTION
**Pull request by gracjan**

### CODE REVIEW

**Comment by gracjan** [comment]
Ugh, I give up. I find no way to run ERT under Emacs23 and that rules out support for Emacs23.

**Comment by gracjan** [comment]
Well, at least ERT works now. But tests do not look good at all.

**Comment by gracjan** [comment]
It wasn't that bad after all. I'll clean this up a little and then we can see if we want emacs23 or not.

**Comment by purcell** [comment]
Nice work! Ping me when you consider this ready to merge.

**Comment by gracjan** [comment]
Clean to merge!

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
