### PR TITLE
Add completing-read for interactive-mode-history

### PR DESCRIPTION
**Pull request by tsukimizake**
A reform of  https://github.com/haskell/haskell-mode/pull/935 .

### CODE REVIEW

**Comment by gracjan** [comment]
Look at #833. It describes how to do this correctly.

**Comment by tsukimizake** [comment]
Thanks. Amended.

**Comment by gracjan** [comment]
This is still not connected to anything, is it?

**Comment by tsukimizake** [comment]
Currently, it can be called by `M-x haskell-interactive-mode-history-completing-read`.
Should I bind it to some key? Should it be `C-c C-h` or something?

**Pull request closed without merging**
