### PR TITLE
Clean up examples directory

### PR DESCRIPTION
**Pull request by gracjan**

### CODE REVIEW

**Comment by gracjan** [comment]
@purcell? Those files are more confusing than good.

**Comment by purcell** [comment]
I can see how they might be helpful for testing, so perhaps an alternative would be to rename `examples` to `test`.

**Comment by gracjan** [comment]
@purcell: I tried to use those in my recent endavours in `haskell-simple-indent` and `font-lock` and, trust me, they are not useful.

**Comment by purcell** [comment]
Okay then. :-)

**Pull request merged**
