### PR TITLE
Parse unindented where-clause properly

### PR DESCRIPTION
**Pull request by k-bx**
Test for https://github.com/haskell/haskell-mode/issues/883

### CODE REVIEW

**Comment by gracjan** [comment]
This still does not build, although it seems okay. Can you rebase over master and push again?

**Comment by gracjan** [comment]
@k-bx, ping. Can you rebase on master and force push it again?

**Comment by k-bx** [comment]
Will do now

**Comment by k-bx** [comment]
@gracjan rebased

**Pull request merged**
