### PR TITLE
Merge hsc-mode into haskell-mode.

### PR DESCRIPTION
**Pull request by gracjan**

### CODE REVIEW

**Comment by gracjan** [comment]
@purcell: I would appreciate a review and a merge.

**Comment by purcell** [comment]
What's the reason for this one?

**Comment by gracjan** [comment]
Cleanup. haskell-c gave exactly nothing as haskell-mode also did font-lock `#if..#else..#endif` and other preprocessor directives.

There was nothing more in there.

**Comment by purcell** [comment]
Makes sense, then. Thanks.

**Pull request merged**
