### PR TITLE
[WIP] Replace haskell-indentation-mode tokenizer, fixes #1369

### LINKED ISSUE #1369: Unclosed string literal causes Emacs to freeze
#### Description
Emacs freezes (unresponsive, 100% CPU) when editing a particular Haskell file:
https://gist.github.com/kvelicka/217ae60620acec3990c448dfa8299c32

Note that the string literal on line 6 is missing the trailing double quote character. If this character is put back, the freeze no longer occurs.

I moved this issue here after initially submitting it to Spacemacs but later realising this is a haskell-mode bug. I have reproduced it on a fresh Xubuntu 16.04 VM and Emacs 25.1, as well as the spacemacs-generated information in the "System Info" section below.

#### Reproduction guide
- Start Emacs
- Open the above-mentined gist as a file with emacs
- Go to the end of line 7
- Press enter (i.e. insert a newline)

*Observed behaviour:*
Emacs freezes - becomes completely unresponsive and (presumably) goes into an infinite loop as CPU usage goes to 100% (of one core) and stays there seemingly indefinitely.

*Expected behaviour:*
A new line is inserted and cursor is placed in it

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t

### PR DESCRIPTION
**Pull request by kvelicka**
Added a test for #1369. Note that this test neither passes nor fails, it freezes up the test suite!

@gracjan: If there is a way to stop it from doing that, or you'd like me to add/expand anything in this PR please let me know and I'll try to fix it.

### CODE REVIEW

**Comment by gracjan** [comment]
The plan is to replace hand made tokenizer in `haskell-indentation-mode` with the solid one in `haskell-lexeme`. Can you try to do this? Thanks.

**Comment by kvelicka** [comment]
I expect to face quite a bit of turmoil in the next month or two so cannot
promise anything immediate.

However, I am interested in learning a bit more about elisp and this would
likely fit the bill. So, I'll try to see what I can do about the tokenizer
but cannot give a definite timeframe for it.


Best wishes,
Karl Velicka

**Comment by gracjan** [comment]
Closing in favor of #1393.

**Comment by kvelicka** [comment]
Sweet, great news!

**Pull request closed without merging**
