### PR TITLE
Add support for type/data family declarations.

### PR DESCRIPTION
**Pull request by yuriy0**
While type families are not part of the either the Haskell 98 or 2010 standards, they have become nearly ubiquitous. It would be nice for the syntax highlighter to support type/data family declarations. It, perhaps coincidentally, supports type/family *instance* declarations, but the word `family' is not highlighted in either 

```
type family X 
data family Y
```

This patch highlights the above correctly.

### CODE REVIEW

**Comment by gracjan** [comment]
Thanks.

Have you checked if `haskell-indentation` works? It usually requires a couple of changes after learning a new keyword it needs to know how to handle it.

**Comment by gracjan** [comment]
Please remove the change in `haskell-indentation`. It does not help but may break things.

Does not help here:

```haskell
data family X
= X
```

breaks things here:

```haskell
func x = do
  family <- x
```

**Comment by gracjan** [comment]
@yuriy0: Can you update this one? It would be really good to merge (but haskell-indentation part must be removed).

**Comment by gracjan** [comment]
@yuriy0: Can you update this one as described?

**Comment by gracjan** [comment]
@yuriy0: ping!

**Comment by gracjan** [comment]
@yuriy0, ping.

Is there anybody that would like to take over these changes?

**Comment by bergey** [comment]
I can adopt this one, but I can't get to it real soon.  Ping me if I haven't finished in 3 weeks?  Of course, if someone else gets to it sooner, that's great.

**Comment by gracjan** [comment]
@bergey: Can you take care of this one? Would be great!

**Comment by bergey** [comment]
Thanks for the reminder.  Will do.

**Pull request closed without merging**
