### PR TITLE
Update completion section

### PR DESCRIPTION
**Pull request by geraldus**
@gracjan I want to add «Tags» section (looks like there nothing about tags in docs!), but do not know:
+ what is the best place for it
+ and how to make a hyperlink to that section

Related #1184

### CODE REVIEW

**Comment by gracjan** [comment]
Put this section anywhere and we will clean up later. Relevant documentation:

- [`@xref`](https://www.gnu.org/software/texinfo/manual/texinfo/html_node/_0040xref.html)
- [`@node`](https://www.gnu.org/software/texinfo/manual/texinfo/html_node/Writing-a-Node.html)
- [`@chapter`](https://www.gnu.org/software/texinfo/manual/texinfo/html_node/Chapter-Structuring.html)

**Comment by geraldus** [comment]
Oh, @gracjan , did you know that GHC can generate tags too?

**Comment by geraldus** [comment]
@gracjan I do not understand how to create link properly, I tried to move Tags section but this does not helps.

**Comment by gracjan** [comment]
This looks good so I merged it. We can work on structure and links when there is more content.

**Comment by geraldus** [comment]
@gracjan but on-line manual was not updated due to error.

**Comment by gracjan** [comment]
oh

**Comment by gracjan** [comment]
I thought this is coveralls failing... silly me.

**Comment by geraldus** [comment]
@gracjan so, can you suggest how to fix this?

**Pull request merged**
