### PR TITLE
More loading

### PR DESCRIPTION
**Pull request by deepfire**
This mimics the `ghc-mod` experience.

### CODE REVIEW

**Comment by deepfire** [comment]
My problem with this is -- I cannot figure out the reason for the `haskell-process-load-file` error in the test suite.  It works fine outside of test..

**Comment by geraldus** [comment]
@deepfire maybe `(require 'haskell)` is needed in `haskell-mode.el`, because `haskell-process-load-file` is defined there.

**Comment by deepfire** [comment]
@geraldus, but haskell.el already requires haskell-mode!

**Comment by deepfire** [comment]
Perhaps the tests are constructed in a wrong way..

**Comment by deepfire** [comment]
TBH I don't understand when haskell.el is supposed to be loaded.

**Comment by deepfire** [comment]
Closing in favor of https://github.com/haskell/haskell-mode/pull/780

**Pull request closed without merging**
