### PR TITLE
Switch from signal to throw/catch in haskell-indentation

### PR DESCRIPTION
**Pull request by gracjan**

### CODE REVIEW

**Comment by gracjan** [comment]
@kuribas: Can you review this pull request?

**Comment by kuribas** [comment]
I originally had throw/catch in my implementation.  Someone changed it to signal, I am not sure why?

**Comment by gracjan** [comment]
You can use git blame in haskell-mode repo or git blame in nilcons repo.

**Comment by kuribas** [comment]
Ok, I see I had error originally, and it was changed to parse-error.  Using throw/catch makes sense.  It should not be necessary to prefix the haskell-indentation-parse-error symbol, just parse-error would be safe enough.  Though you can keep it if you like it.

**Pull request merged**
