### PR TITLE
Stylish haskell rebase master

### PR DESCRIPTION
**Pull request by WraithM**
Sorry for the confusion with PRs :( I did the rebase onto master, and tried to update the old PR, and github closed the PR.

So, I'm trying to learn about the `unwind-protect` thing. I'll update this PR with that fix.

### CODE REVIEW

**Comment by WraithM** [comment]
Okay @gracjan, I'm finally done with this PR! I'm sorry it took so long...

**Comment by WraithM** [comment]
@gracjan, is there anything else you need from me to get this merged in?

**Comment by gracjan** [comment]
Code looks good, somebody needs to check this out in practice (I mean somebody else than you, we want second pair of eyes).

**Comment by bergey** [comment]
I'll run this for a couple of days & report back.

**Comment by WraithM** [comment]
Thanks @bergey

**Comment by gracjan** [comment]
@bergey: And? How does this work?

**Comment by gracjan** [comment]
Okay, I'm taking this over. I'll write some tests around this functionality. Will submit new PR.

**Comment by gracjan** [comment]
Here is the new version #1333.

**Pull request closed without merging**
